### ISSUE TITLE
TypeError in console

### ISSUE THREAD

**Issue by adnansarajlic** [archfz/cypress-terminal-report#135]
Hi,

I started to see those errors:
![Anteckning 2022-02-18 140824](https://user-images.githubusercontent.com/28649112/154688613-db9d362c-39d6-4bda-afca-5776430dde35.jpg)

Cypress 8.7.0
cypress-terminal-report 3.4.2

**Comment by archfz** [comment]
In the plugin there is nowhere any property named `steps`.

The errors is coming from your code. Look at the error stack trace, not where the error got console logged (the first line). The reason you see on first line `LogCollectBrowserConsole.js` is because we are overriding the `console.error` function in order to be able to catch and collect them, and thus we call the actual original `console.error` in the plugin.

See https://github.com/archfz/cypress-terminal-report/blob/751ca3a815fa90fd6f751e909735ae2d882abb37/src/collector/LogCollectBrowserConsole.js#L53
