### ISSUE TITLE
Option to filter out messages from beforeEach and afterEach

### ISSUE THREAD

**Issue by Josh68** [archfz/cypress-terminal-report#170]
Hello, and thanks for this plugin. Is there a way, or could it be implemented, to filter out messages from `beforeEach` and/or `afterEach` blocks, to focus on logs only inside specs? I'm trying to wrap my head around doing this using the custom log collector, but wonder if there could be a simpler way.

**Comment by archfz** [comment]
Hi. Currently there is no such feature. Also I am not aware at this point if we can detect whether a cypress command was registered in an after each hook. So the steps would be:

1. Do some debugging in `npx cypress open` to determine if logs from commands have any information based on which we could determine if they were registered in an `it` or and `afterEach/beforeEach`  block.
2. Implement a plugin config to exclude these if 1. passes.

However there are some considerations to be made: what happens if failure happens during a command from  `afterEach/beforeEach` ? Maybe in this case we could ignore the option and still log from these blocks.

Contribution is welcome. I can help with directions.

**Comment by Josh68** [comment]
Thanks, @archfz, I'll look into options and let you know if I need help. I was also thinking maybe I could look at just filtering on particular content in log messages, e.g. a regex pattern

**Comment by Josh68** [comment]
@archfz, somewhat related question. 

Do you by chance know if there's a way to pick up `Cypress.env` settings when calling the support install function? I've tried simply adding an `env` config to one of my spec `describe` functions, but these apparently don't get picked up at the right point to be available in my support file (in my case, `/support/e2e.ts`. Maybe there's another way I haven't figured out? 

If this were possible, it would allow me to add logging to terminal only for tests where I really want it, and not being able to ignore `cy.log`s in `beforeEach` and `afterEach` callbacks wouldn't be a big deal.

Thanks

**Comment by archfz** [comment]
I think your idea will not work, as `/support/e2e.ts` is executed only once on `cypress run`. Meaning if you have the plugin support install in `/support/e2e.ts` and you have 10 specs in the run, you cannot differently install the plugin per spec, since it only installs once.

Now there might be the idea of doing the plugin install in the describe block of a spec instead. But I doubt that would work either, as I am not sure if event listeners would be cleaned up after that spec finishes, and you will end up either with multiple event listeners registering.

On the other hand, if you only want to filter out for which spec to collect logs, that would be an easier feature to implement in this plugin.

**Comment by Josh68** [comment]
Thanks, @archfz. I'll continue to look at the possibility of filtering either by spec name(s) or log message content. Sounds like I was just trying something that isn't possible given the order of operations in the Cypress runner.

**Comment by Josh68** [comment]
Solution that works for my situation, testing my meager TypeScript skills / understanding.

```js
filterLog: function(
    args: [
      cypressTerminalSupportLogsCollector.LogType,
      string,
      cypressTerminalSupportLogsCollector.Severity
    ]
  ) {
    const [logType, message] = args;
    return logType === "cy:log" && message.includes("***"); // 'magic' string that we include in logs meant to replace `it` `title` strings
  },
});
```

I still left in `collectTypes: ["cy:log"]`, though not sure it's necessary.

**Comment by Josh68** [comment]
Since I found a satisfactory solution, closing. If you're interested, I could add something to documentation (i.e., an example) but seems like that would require providing examples for much more of the API, and I'm suspecting neither of us have the time for that right now.

**Comment by archfz** [comment]
If that solution is ok for you, it's ok to close. If other have demand for this we shall reopen

**Comment by Josh68** [comment]
So far, doing what I wanted, which is just to limit logging to specific kinds of logs (could be in any spec block, but doesn't matter). I wasn't entirely clear on how to use it, or really how to get the typing right, until I fiddled with it for a while. Thanks for your help.
