### ISSUE TITLE
cons:log logs are omitted when using in conjunction with reporter plugins

### ISSUE THREAD

**Issue by albadam000** [archfz/cypress-terminal-report#28]
First of all, thank you for the plugin and implementing the file output, great stuff (koszonjuk szepen)!

We are using cypress in conjunction with ReportPortal which is an open source test reporting and aggregation solution. We are using [agent-js-cypress](https://github.com/reportportal/agent-js-cypress) plugin to push the test results and logs to ReportPortal, and [cypress-multi-reporters](https://github.com/you54f/cypress-multi-reporters) to allow generating multiple log outputs at the same time (we need agent-js-cypress for ReportPortal and mocha, mochawesome for other systems).

Problem:
1. When using cypress-terminal-report with cypress-multi-reporters, the majority of the logs are omitted. I think all the cons:log (K):  calls are not shown in the output file or in the console; only the cy:command and cy:xhr calls are there.

2. When using cypress-terminal-report in conjunction with agent-js-cypress, the [ReportPortal custom commands ](https://github.com/reportportal/agent-js-cypress#reportportal-custom-commands) in the latter are not working. Reason might the that both plugins are overriding the cy.log() command?

Happy to further assist with debugging or share code snippets if necessary. Thanks in advance.

**Comment by archfz** [comment]
cy.log, cy.request, cy.server and also browser console logs are overwritten to allow capturing them. In noth cases tough at least in this module the overwritten functions are called by us, so this needs indepth investigation.

For now what I could suggest is considering the file report formats provided by this plugin.

**Comment by albadam000** [comment]
Thank you for the quick reply. Unfortunately, ReportPortal is a hard requirement for us, so can't get rid of it for now. I raised the issue with cypress-multi-reporters as well, maybe they can do something on their side.
In the meanwhile let me know if I can assist with the investigation.
Thanks

**Comment by archfz** [comment]
@albadam000 Well first we would need to understand how cypress.overwrite actually works. If used multiple times on the same command on the same project does it create inheritance or not: if the answer to this is no we need to go to cypress to ask for support. For this you could attempt to find the code where reportportal intercepts these calls and set a breakpoint, then also for cypress-terminal-report set a breakpoint in installLogsCollector.js in the callback at Cypress.overwrite('log'. This way you can see which of them executes and in what order. 

Have you ever configured a node js debugger with your ide? If you have webstorm its quite easy.

**Comment by albadam000** [comment]
I just set up the debugger with my VS Code. Will look into it further over the next 1-2 days (it's getting late in Australia now).
Thanks for the help.

**Comment by YOU54F** [comment]
If you can provide a repository with a minimal example and a sample of the expected log output that would be great in investigating

**Comment by archfz** [comment]
@albadam000 Any progress? Can we provide any help?

**Comment by albadam000** [comment]
I tried to reproduce the issue, but can't repro it consistently anymore. I'm observing an inconsistent behaviour and couldn't find the pattern yet.
One thing that's consistent is I'm getting empty logs for successful test runs even if printLogs: 'always' is set.
I'll try again with the latest version tomorrow. Sorry for the delay.

**Comment by albadam000** [comment]
What would be the best place to start the investigation?

**Comment by archfz** [comment]
Well I would say that you start with what is consistent. Finding an issue with that might give clues to the inconsistent issue as well.

If you have configured your debugger it should be quite straight forward; otherwise you can also just add console.log in the right places to see where execution fails. `printLogs: always` has an effect specifically in **[installLogsCollector.js](https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsCollector.js#L75)**, you could add a breakpoint here in the first place to see if the code in the if is executed at least in case of the passing tests (or not passing ones if in both you get empty logs). If it is not executed you can add a breakpoint on the if to see why it's not. If it is executed you should see in [installLogsPrinter.js](https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsPrinter.js#L40) what is happening and why it is not printing those logs.

It is important to note that breakpoints in the installLogsCollector.js file you should write with the `debugger;` js keyword and let the tests execute in cypress GUI with inspector open. This is easy to do and this breakpoint will open the inspector debugger automatically when the execution reaches it.
In case of the installLogsPrinter.js, which is executed on Node.js level, you would need your IDE`s support to do debugging, or just write console.log`s to inspect what gets executed and with what data.

**Comment by albadam000** [comment]
I added console logs to some places in installLogsCollector.js, but the output from console.log is not showing up on the console I assume because of this: https://github.com/cypress-io/cypress/issues/3199

**Comment by albadam000** [comment]
The config object is empty, and config.printLogs is undefined here:
https://github.com/archfz/cypress-terminal-report/blob/c412b3a8a8c7a8f7cddf10b9b4a409b4baa7180a/src/installLogsCollector.js#L75

This is how my plugins/index.js looks like:
`module.exports = (on, config) => {

  const options = {
    printLogs: 'always',
    outputRoot: config.projectRoot + '/logs/',
    outputTarget: {
      'out.txt': 'txt'
    }
  };
 
  require('cypress-terminal-report').installPlugin(on, options);
}`

**Comment by archfz** [comment]
You need to add that option to the support install. Check readme

**Comment by albadam000** [comment]
Yes figured it out in the meanwhile, logs are now created even for passing tests. Will continue with the original issue.

**Comment by albadam000** [comment]
I can't reproduce the issue anymore. Feel free to close it. Thank you for your support.

**Comment by archfz** [comment]
@albadam000 Thanks as well. So basically it is now compatible with the other plugin right.
