### ISSUE TITLE
Uncaught TypeError: Cannot set property '2' of undefined

### ISSUE THREAD

**Issue by zvaehn** [archfz/cypress-terminal-report#31]
I am getting this error when running all tests.
This does not occure in single runs.

I figured out that checking for undefined in [here](https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsCollector.js#L65) fixes the issue as well as resetting 
```js
logsChainId = {};
```
in the `.on('test')` callback [here](https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsCollector.js#L70).

Looking forward to hear any feedback or see any fixes.

Best,
Sven

**Comment by archfz** [comment]
Are you getting this only in tests? As I look at it this might be a real live issues. The problem I might see here is that we have the collect types and filter logs options that could make it so that those logs that get updated we dont store them actually.

So an easy fix would be just to simply check if there is that key in the logs.

**Comment by zvaehn** [comment]
Yes, i am only getting this in tests and if i edit the File as described above the error is gone.
Sure i could filter out error messages but this is more like a workaround.
I don't know the code as good as you do, so i hoped that you might approve my fix suggestions, knowing that this is just a check to prevent the error, not resolving the error in its origin.

**Comment by archfz** [comment]
Released in 1.4.0
