### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by Morriz** [archfz/cypress-terminal-report#37]
Hi, it would be nice if you could support typescript as well, knowing that cypress supports it out of the box now.

**Comment by archfz** [comment]
@Morriz what do you mean by typescript ?

**Comment by Morriz** [comment]
Aha, I think you would have to export the types for your javascript exports in a separate `.d.ts` file.

**Comment by archfz** [comment]
I am not sure I follow. Do you mean that this plugin is not usable if you have webpack with typescript enabled for cypress?

**Comment by archfz** [comment]
Or do you mean that we should write this plugin in typescript? I think it's not that important for this module to be in typescript.

**Comment by archfz** [comment]
@Morriz ?

**Comment by Morriz** [comment]
> I am not sure I follow. Do you mean that this plugin is not usable if you have webpack with typescript enabled for cypress?

No, it’s usable as is, but with the types added it works with ts as well. There are probably some type inference tools out there so you can build it

**Comment by Morriz** [comment]
https://www.typescriptlang.org/v2/docs/handbook/declaration-files/dts-from-js.html

**Comment by archfz** [comment]
I still don't quite get what the requirement would be here.
1. Transform this repository to be written in typescript? - I think there is no need for it, I don't expect too much growth on this repo at this time
2. Add d.ts files for the install plugin and install support? - If this is what you are asking then I will leave this task; but still there is not much value to gain from it. It would only help a bit with the options typing. But since cypress either way uses .js for the support.js and plugin.js I don't even think it would work.

**Comment by Morriz** [comment]
I allows TS now everywhere...also plugins and support

**Comment by SgtPooki** [comment]
It would work if you add types. Types do not hinder a js package in any way except for maintenance. But you can still write your package in js, and use `//@ts-check` and even benefit from your own type definitions.

**Comment by archfz** [comment]
@SgtPooki If types in need we should transform the whole code to typescript. It wouldnt be that hard and in that way we can generate also automatically d.ts file. This could be a good exercise so help on this is welcome.

**Comment by archfz** [comment]
Done in #52. Coming up in next release.

**Comment by archfz** [comment]
Released in 2.1.0.
