### ISSUE TITLE
Getting error mixing `cy.request` with `cy.now`

### ISSUE THREAD

**Issue by sergeyKhristenko** [archfz/cypress-terminal-report#44]
Hello! First of all thank you for this plugin!

However, there is an error I'm stuck with. Getting this error when mixing `cy.now` with `cy.request` and `cy.wrap`:
![image](https://user-images.githubusercontent.com/18219232/90828178-3c78ff80-e346-11ea-8494-24ae498b1f5b.png)

Steps to reproduce:
``` javascript
it('cy.request + cy.now', function () {
  cy.wrap(true).then(() => {
    return cy
      .now('request', {
        url: `http://google.com`,
      })
      .then(($res) => cy.wrap($res, { log: false }));
  });
});
```

I see that the plugin overwrites `request` and `server`. Maybe it makes sense to make `request` and `server` logs configurable(turn on/off)?

**Comment by archfz** [comment]
Hi. This is not related to the plugin. I think you should not be using cy.now in the tests as it is meant for debugging and especially only used in the browser console. See https://docs.cypress.io/guides/guides/debugging.html#Run-Cypress-command-outside-the-test . Also you don't need cy.wrap. You can just do directly cy.request(..). 

Also the error is pointing to a logic issue somewhere. Please note that all cy command add to a queue that will only start executing once your current execution context finished (all queuing finished). Attempting to add additional cy commands on this queue during async execution will produce this error since cypress detects that something was queued while it's executing the queue and it doesn't know where to put this new command.
