### ISSUE TITLE
commands from 'before' hook are missing in the report

### ISSUE THREAD

**Issue by sergeyKhristenko** [archfz/cypress-terminal-report#55]
I've noticed that commands from `before` and `after` hooks don't show up in the report(`beforeEach` and `afterEach` works fine). Not quite sure, but it looks like [this logs](https://github.com/archfz/cypress-terminal-report/blob/master/src/installLogsCollector.js#L88) overwritten at some point.

Also, couldn't find any test for hooks so not sure if it's some kind of regression.

I'm using cypress 4.12.0 if it's matters.

A test case could be just something like:
``` javascript
describe('Always red test', function () {
  before(function () {
    cy.log('from before');
  });
  beforeEach(function () {
    cy.log('from beforeEach');
  });
  after(function () {
    cy.log('from after');
  });
  afterEach(function () {
    cy.log('from afterEach');
  });
  it('passed it', function () {
    cy.log('from it');
  });
});
```

**Comment by archfz** [comment]
I've checked all the way back till 1.1.0. This seems like after and before command registrations never worked. So I will marked this as an enhancement.

The question here is infact that how should we treat these? Because these are not per tests but per spec file, but we are logging per test (as we have also the feature to log only failed tests). Should we add what's from before and after hooks to each tests logs from that spec file? Maybe treat somehow all logs from before and after as special cases of tests and log them as such (in case of log only on fail, log them only if any of the tests fail on spec).

**Comment by archfz** [comment]
@sergeyKhristenko What do you say about the proposed way to treat after and before logs?

**Comment by FLevent29** [comment]
Can try to do it.

**Comment by sergeyKhristenko** [comment]
@archfz sorry, missed your message. If I understand correctly it would be something like
```
specname.js
  before: commands from before

  test1: commands from test1
  test2...

  after: commands from after
```
or whatever the order will be.
that would be great!

**Comment by sergeyKhristenko** [comment]
@FLevent29 any updates on this?

**Comment by FLevent29** [comment]
Sorry, I haven't worked on it for a little more than a while now. I'm going to try and do it in the following days.

**Comment by FLevent29** [comment]
Sorry I sat on this issue for so long. Even so, I cannot do it, I mean there's probably a way to do it, but you'd have to dig deep into Cypress code to find your answers. Or so I believe. Either way I don't have enough experience for this.

What I found for `Cypress.mocha.getRunner().on(/*constant here*/, function() { ... })`:
- listening to `EVENT_TEST_BEGIN` (`test`) for `before()` hooks only occur when `before()` is successful thus defeating the purpose
- `EVENT_TEST_END` (`test end`) for `after()` doesn't seem viable, it's an `afterEach()` more or less
- `EVENT_SUITE_BEGIN` (`suite`) for `before()` didn't work correctly, and couldn't figure out how it put the whole thing into an infinite loop during my final tests
- `EVENT_SUITE_END` (`suite end`) only goes through at the very last `cy.task()` for some reason, otherwise would be almost ideal
- `EVENT_TEST_FAIL` (`fail`) doesn't go through with `cy.task()` at all

The rest don't really seem useful, maybe someone could try and have a second opinion on this.

**Comment by archfz** [comment]
@FLevent29 if you have a branch you have worked on please provide the link for it, even if it's only draft changes.

**Comment by archfz** [comment]
As I see either we are missing something or we will need support from cypress to be able to implement this. Anyone else welcome to attempt implementing this. A fresh I might notice some backdoor to the implementation.

**Comment by archfz** [comment]
This was real hard, but I've dived deep in cypress and mocha to hack in a solution. Unfortunately the number of twisted logic and prototype pollution required makes this feature probably unstable. The feature can be enabled in 3.0.0 with the flag optionsenableextendedcollector
